[[getting-started]]
== Getting Started

Add everything a developer needs to know to start using your project, including:

* System Requirements (if any)
* Installation instructions (usually how to set it up in Maven, Gradle, or both)
* The simplest possible application that uses your project
* A somewhat more complex application that shows a key feature

To help readers find the content they want more quickly, add a list of the headings at the
next level (for example, level 3 if the current headinng is level 2). (As mentioned in the
separate document that offers writing advice, called writing-advice.adoc, this technique
is called information mapping.)

* <<getting-started-system-requirements>>
* <<getting-started-installation>>
* <<getting-started-starter-application>>
* <<getting-started-complex-application>>



[[getting-started-system-requirements]]
=== System Requirements

If you project requires anything special by way of memory or disk space or other
infrastructure (including a Cloud Foundry or other cloud instance), describe how to set up
those bits here.



[[getting-started-installation]]
=== Installation

Describe how to install your project here. That may be nothing more than how to get it
into Maven, Gradle, or both. However, it may also include local setup options (perhaps for
testing) and cloud setup options.



[[getting-started-starter-application]]
=== A Starter Application

The following example shows the simplest possible application that can be built with {Your
Project}:

[source,java]
----
// Your application goes here
----



[[getting-started-complex-application]]
=== A More Complex Application

// If you can make a more specific heading, do so. One good idea is to get the name of the
// feature you want to showcase in the heading.

The following example shows a more complex application that includes how to {use some key
feature of Your Project}:

[source,java]
----
// Your application goes here
----



[[getting-started-what-to-read-next]]
=== What to Read Next

If you have a "`What to Read Next`" section in your overview chapter, you should have one
in the other chapters (except for the last chapter and any appendices).
